from __future__ import annotations

from typing import Optional, Protocol

from ...shared.models import Channel


class PlayersRepository(Protocol):
    async def upsert(self, tg_user_id: int, username: Optional[str], first_name: Optional[str]) -> int: ...

    async def get_classic_games(self, user_id: int) -> int: ...

    async def get_draw_count(self, user_id: int) -> int: ...

    async def set_favorite(self, user_id: int, channel_id: Optional[int]) -> None: ...

    async def get_favorite(self, user_id: int) -> Optional[Channel]: ...

    async def get_reward_stage(self, user_id: int) -> int: ...

    async def set_reward_stage(self, user_id: int, stage: int) -> None: ...

    async def is_deathmatch_unlocked(self, user_id: int) -> bool: ...

    async def mark_deathmatch_unlocked(self, user_id: int) -> None: ...

    async def get_deathmatch_games(self, user_id: int) -> int: ...
